name : Build and Push Image to Docker Hub
on:
    push:
        branches:
            - main
    
jobs:
    explore:
        runs-on: ubuntu-latest
        steps:
            - run: echo "hello github actions"
            